# this one seems to work but causes delays
#[global]
#chord_timeout = 300

#[main]
#leftalt+leftshift+left = S-home
#leftalt+leftshift+right = S-end


# this one works on ubuntu on the laptop, maybe elsewhere

[ids]
048d:c999

[main]
#leftbrace+leftalt+leftshift  = macro(press(leftcontrol), press(tab), release(tab), release(leftcontrol))
#rightbrace+leftalt+leftshift = macro(press(leftcontrol), press(leftshift), press(tab), release(tab), release(leftshift), release(leftcontrol))
#left+leftalt+leftshift = S-home
leftalt = layer(alt)

[alt+shift]
left = S-home 
right = S-end
